import { ButtonDoc } from './elements/buttondoc';
import { DividerDoc } from './elements/dividerdoc';
import { HeaderDoc } from './elements/headerdoc';
import { ImageDoc } from './elements/imagedoc';
import { InputDoc } from './elements/inputdoc';
import { LabelDoc } from './elements/labeldoc';
import { ListDoc } from './elements/listdoc';
// import { LoaderDoc } from './elements/loaderdoc';
import { RailDoc } from './elements/raildoc';
import { RevealDoc } from './elements/revealdoc';
import { SegmentDoc } from './elements/segmentdoc';

exports.ButtonDoc = ButtonDoc;
exports.DividerDoc = DividerDoc;
exports.HeaderDoc = HeaderDoc;
exports.ImageDoc = ImageDoc;
exports.InputDoc = InputDoc;
exports.LabelDoc = LabelDoc;
exports.ListDoc = ListDoc;
exports.RailDoc = RailDoc;
exports.RevealDoc = RevealDoc;
exports.SegmentDoc = SegmentDoc;